version: "3.9"

services:
  db:
    image: postgres:17
    container_name: mmotors_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Motdepasse123
      POSTGRES_DB: motors
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: mmotors_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:Motdepasse123@db:5433/motors

volumes:
  postgres_data: